server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/security
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  #        show_sql: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ABn5CQF1i1WioNmERIfy
            client-secret: ${{secrets.NAVER_CLIENT_SECRET}}
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          google:
            client-id: 143667160680-56cpb80as4f6onvs0mkc9slm2v516n6f.apps.googleusercontent.com
            client-secret: ${{secrets.GOOGLE_CLIENT_SECRET}}
            scope:
              - email
              - profile
      - provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # ????? json ?? ? response ?? ? ??? ???? ?????.

logging:
  level:
    sql: debug
    org.hibernate.type: trace