server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/security
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  #        show_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 143667160680-56cpb80as4f6onvs0mkc9slm2v516n6f.apps.googleusercontent.com
            client-secret: ${{secrets.GOOGLE_CLIENT_SECRET}}
            scope:
              - email
              - profile

logging:
  level:
    sql: debug
    org.hibernate.type: trace